services:
  - type: web
    name: fifteen-savebot
    env: python
    region: oregon
    plan: hobby
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8467727619:AAFNrGOTll1DbQvTGyeUtbwL7pJXhAuCP38
    runtime: python
    pythonVersion: 3.11.11
